import unittest


class TestKubernautErrors(unittest.TestCase):

    def test_service_connection_failure_gracefully_errors(self):
        pass

    def test_claim_same_name_gracefully_errors(self):
        pass
